name: CI/CD
on:
  push:
    branches:
      - main
      with:
    ref: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       # Build Docker image
      - name: Build Docker image
        run: docker build -t my-backend:latest ./Lab4

      # Push image to Docker Hub
      - name: Push Docker image
        run: docker tag my-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # script: |
          #   docker stop backend || true
          #   docker rm backend || true
          #   docker build -t my-backend .
          #   sudo docker run -d -p 8000:8000 --name backend my-backend




